version: '3'
services:

  # The Application
  app:
    build:
      context: ./app/
      dockerfile: app.dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./app/:/var/www/
      - ./php/php.ini:/usr/local/etc/php/conf.d/my-custom-php.ini
  # The Web Server
  web:
    build:
      context: ./web/
      dockerfile: web.dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./web/:/etc/nginx/conf.d/
      - ./ssl/:/etc/nginx/ssl/
      - ./app/:/var/www/
    ports:
      - 80:80
      - 443:443

  # The Database
  database:
    image: mysql:8.0.22
    restart: always
    volumes:
      - ./db/dbdata:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
    ports:
        - "3306:3306"

volumes:
  dbdata:
  my.cnf:
